version: '3.9'
services:

  product:
    container_name: product
    image: ecomm-product
    build: ./product
    ports:
      - 3001:3001
    depends_on:
      - mongodb

  account:
    container_name: account
    image: ecomm-account
    build: ./account
    ports:
      - 3002:3002
    depends_on:
      - mongodb
      - redis

  order:
    container_name: order
    image: ecomm-order
    build: ./order
    ports:
      - 3004:3004
    depends_on:
      - mongodb

  finance:
    container_name: finance
    image: ecomm-finance
    build: ./finance
    ports:
      - 3003:3003
    depends_on:
      - mysql

  redis:
    image: redis
    volumes:
    - redis-ecomm:/data
    container_name: redis-ecomm
    restart: always
    ports:
    - 6379:6379

  mongodb:
    container_name: mongo-ecomm
    image: mongo:5.0.14
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-ecomm:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      
  mysql:
    container_name: mysql-ecomm
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-ecomm:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecomm_finance

volumes:
  mongo-ecomm:
  mysql-ecomm:
  redis-ecomm: