version: '3.9'
services:

  product:
    container_name: product
    image: ecomm-product
    build: ./product

  account:
    container_name: account
    image: ecomm-account
    build: ./account

  mongodb:
    container_name: mongo-ecomm
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-ecomm:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      
  mysql:
    container_name: mysql-ecomm
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-ecomm:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mongo-ecomm:
  mysql-ecomm: