openapi: 3.0.3
info:
  title: Ecomm - API Products
  description: API para consultar, adicionar, atualizar e remover categorias e produtos
  version: 1.0.0
  termsOfService: https://mockapi.io/docs
  contact:
    name: Rhian Moura
    email: rhian.moura@pagonxt.com
  license:
    name: Licença Pública
    url: https://www.gnu.org/licenses/gpl-3.0.html
servers:
- url: https://63ced172fdfe2764c72b1707.mockapi.io/
  description: API Products
paths:
  /api/categories:
    get:
      tags:
      - Categories
      summary: Lista todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
  /api/categories/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
        example: "63caa785ae701b25441ff0be"
    get:
      tags:
      - Categories
      summary: Recupera uma categoria pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
  /api/admin/categories:
    post:
      tags:
      - Categories
      summary: Cria uma nova categoria. Método somente autorizado à administradores
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Categoria criada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        401:
          description: Desautorizado
          content: 
            aplication/json:
              example: "Acesso Negado! Usuário desautorizado"
  /api/admin/categories/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
        example: "63caa785ae701b25441ff0be"
    put:
      tags:
      - Categories
      summary: Atualiza todas as informações de uma categoria pelo ID. Método somente autorizado à administradores
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
        401:
          description: Desautorizado
          content: 
            aplication/json:
              example: "Acesso Negado! Usuário desautorizado"
    delete:
      tags:
      - Categories
      summary: Deleta uma categoria pelo ID. Método somente autorizado à administradores
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
        401:
          description: Desautorizado
          content: 
            aplication/json:
              example: "Acesso Negado! Usuário desautorizado"
    patch:
      tags:
      - Categories
      summary: Ativa o status de uma categoria pelo ID. Método somente autorizado à administradores
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
        401:
          description: Desautorizado
          content: 
            aplication/json:
              example: "Acesso Negado! Usuário desautorizado"
  /api/products:
    get:
      tags:
      - Products
      summary: Lista todos os produtos
      parameters:
        - name: valorMin
          in: query
          description: Valor mínimo dos produtos
          schema: 
            type: number
            format: double
        - name: valorMax
          in: query
          description: Valor máximo dos produtos
          schema: 
            type: number
            format: double
        - name: categoria_id
          in: query
          description: Produtos da categoria especificada
          schema: 
            type: string
            format: uuid
        - name: qntdEstoqueMin
          in: query
          description: Produtos com quantidade superior à especificada
          schema: 
            type: integer
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /api/products/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
        example: "63caa785ae701b25441ff0be"
    get:
      tags:
      - Products
      summary: Recupera um produto pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Produto não encontrado
          content:
            application/json:
              example: "Not found"
  /api/admin/products:
    post:
      tags:
      - Products
      summary: Cria um novo produto. Método somente autorizado à administradores
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        401:
          description: Desautorizado
          content: 
            aplication/json:
              example: "Acesso Negado! Usuário desautorizado"
  /api/admin/products/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
        example: "63caa785ae701b25441ff0be"
    put:
      tags:
      - Products
      summary: Atualiza as informações de um produto pelo ID. Método somente autorizado à administradores
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Produto não encontrado
          content:
            application/json:
              example: "Not found"
        401:
          description: Desautorizado
          content: 
            aplication/json:
              example: "Acesso Negado! Usuário desautorizado"
    delete:
      tags:
      - Products
      summary: Deleta um produto pelo ID. Método somente autorizado à administradores
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Produto não encontrado
          content:
            application/json:
              example: "Not found"
        401:
          description: Desautorizado
          content: 
            aplication/json:
              example: "Acesso Negado! Usuário desautorizado"
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        catgeoria:
          type: string
        status:
          type: string
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nome:
          type: string
        descricao:
          type: string
        slug:
          type: string
        precoUnitario:
          type: number
          format: double
        qntdEstoque:
          type: integer
        categoria_id:
          type: string
          format: uuid